apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-tool-config
  namespace: monitoring-tool
data:
  HTTP_ADDR: ":8080"
  ALLOW_ORIGIN: "*"
  PROMETHEUS_URL: "http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090"
  PROMETHEUS_TIMEOUT_SECONDS: "10"
  PROMETHEUS_SMOKE_QUERY: "up"
  ALERT_EVAL_INTERVAL_SECONDS: "15"
  LOG_LEVEL: "info"
