apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - backend.yaml
  - frontend.yaml
  - incident-agent.yaml
  - prometheus-mcp.yaml
  - prometheus-mcp-official.yaml
  - kubernetes-mcp.yaml
  - kubernetes-mcp-official.yaml
  - ingress.yaml
